---
  - name: Keepalived Configuration Files for Exim
    template:
      src: keepalived.conf.exim-master
      dest: /etc/keepalived/keepalived.conf
      owner: root
      group: root
      mode: 0644
    when:
      - 'role == "master" and service == "exim"'

   
  - name: Keepalived Configuration Files for Exim
    template:
      src: keepalived.conf.exim-slave
      dest: /etc/keepalived/keepalived.conf
      owner: root
      group: root
      mode: 0644
    when:
      - 'role == "slave" and service == "exim"'
    
  - name: Keepalived Configuration Files for Nginx
    template:
      src: keepalived.conf.nginx-master
      dest: /etc/keepalived/keepalived.conf
      owner: root
      group: root
      mode: 0644
    when:
      - 'role == "master" and service == "nginx"'

   
  - name: Keepalived Configuration Files for Nginx
    template:
      src: keepalived.conf.nginx-slave
      dest: /etc/keepalived/keepalived.conf
      owner: root
      group: root
      mode: 0644
    when:
      - 'role == "slave" and service == "nginx"'    

  - name: Keepalived Configuration Files
    template:
      src: checkport.sh
      dest: /etc/keepalived/scripts/checkport.sh
      owner: root
      group: root
      mode: 0644
    when:
      - 'service == "nginx" or service == "exim"'
      
  - name: Keepalived Configuration Files for Redis
    template:
      src: keepalived.conf.redis-master
      dest: /etc/keepalived/keepalived.conf
      owner: root
      group: root
      mode: 0644
    when:
      - 'role == "master" and service == "redis"'

  - name: Keepalived Configuration Files for Redis
    template:
      src: keepalived.conf.redis-slave
      dest: /etc/keepalived/keepalived.conf
      owner: root
      group: root
      mode: 0644
    when:
      - 'role == "slave" and service == "redis"'

  - name: Keepalived Configuration Files for Redis
    template:  
      - { src: 'redis_check.sh', dest: '/etc/keepalived/scripts/' }
      - { src: 'redis_fault.sh', dest: '/etc/keepalived/scripts/' }
      - { src: 'redis_master.sh', dest: '/etc/keepalived/scripts/' }
      - { src: 'redis_slave.sh', dest: '/etc/keepalived/scripts/' }
      - { src: 'redis_stop.sh', dest: '/etc/keepalived/scripts/' }
    when:
       - 'service == "redis"'
      

  - name: Install Keepalived
    shell: |
     sudo systemctl restart keepalived

