---
  - name: Keepalived Configuration Files
    template:
      src: keepalived.conf.exim-master
      dest: /etc/keepalived/keepalived.conf
      owner: root
      group: root
      mode: 0644
    when:
      - 'role == "master" and service == "exim"'

   
  - name: Keepalived Configuration Files
    template:
      src: keepalived.conf.exim-slave
      dest: /etc/keepalived/keepalived.conf
      owner: root
      group: root
      mode: 0644
    when:
      - 'role == "master" and service == "exim"'

  - name: Keepalived Configuration Files
    template:
      src: checkport.sh.exim
      dest: /etc/keepalived/scripts/checkport.sh
      owner: root
      group: root
      mode: 0644
    when:
      - 'service == "nginx" and service == "exim"'
      

  - name: Install Keepalived
    shell: |
     sudo systemctl restart keepalived

